config/routes.rb
RubySwarm::Application.routes.draw do

  devise_for :users

  resources :useragents

  resources :jobs, :except => [:edit, :update] do
    collection do
      get 'run'
    end
  end

  resources :clients, :only => [:index, :show]

  resources :runs, :only => [:update] do
    collection do
      get 'get'
    end
  end

  resources :client_runs, :only => [:show]

  root :to => "welcome#index"

end

app/models/job.rb
class Job < ActiveRecord::Base

  RUNNING = 1
  DONE = 2

  belongs_to :user
  has_many :runs, :dependent => :destroy
  has_many :useragent_runs, :through => :runs
  has_many :client_runs, :through => :runs

  serialize :suites

  attr_accessible :name, :browsers, :suites, :url, :revision, :test_creation_date


  #TODO: Better association validation
  validates :user_id,  :presence => true
  validates :name,     :presence => true, :uniqueness => { :scope => :revision }
  validates :browsers, :presence => true
  validates :suites,   :presence => true

  scope :running, where(:status => RUNNING)
  scope :done, where(:status => DONE)

  before_create :setup_runs, :set_test_creation_date

  def running?
    status == RUNNING
  end

  def done?
    status == DONE
  end

  def browsers=(val)
    self[:browsers] = case val
      when Array, String
        # This helps keep the order
        Useragent::BROWSER_TYPES.select{|b| val.include?(b) }.join
      else
        nil
    end
  end

  def suites=(val)
    self[:suites] = case val
      when String
        Hash[*val.scan(/^(\w+):\s+(\S+)\s*$/).flatten]
      when Hash
        val
      else
        nil
    end
  end

  def run_started
    return false if done? || running?
    update_attribute(:status, RUNNING)
  end

  def run_completed
    return false unless running?
    update_attribute(:status, DONE)
  end

  private

    def setup_runs
      return unless suites

      for name, url in suites
        runs.build(:name => name, :url => url, :browsers => browsers)
      end
    end

    def set_test_creation_date
      self.test_creation_date ||= Time.now
    end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  load_and_authorize_resource :except => :run
  before_filter :authenticate_user!, :only => :run
  before_filter :setup_client,       :only => :run
  protect_from_forgery :except => [:create]

  # GET /jobs
  # GET /jobs.xml
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @jobs }
    end
  end

  def run
  end

  # GET /jobs/1
  # GET /jobs/1.xml
  def show
    respond_to do |format|
      format.html do
        if request.xhr?
          render :partial => 'show', :locals => { :job => @job }
        else
          render 'show'
        end
      end
      format.xml  { render :xml => @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.xml
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @job }
    end
  end

  # POST /jobs
  # POST /jobs.xml
  def create
    @job.user_id = current_user.id
    respond_to do |format|
      if @job.save
        format.html { redirect_to(@job, :notice => 'Job was successfully created.') }
        format.xml  { render :xml => @job, :status => :created, :location => @job }
        format.json { render :json => @job, :status => :created, :location => @job }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @job.errors, :status => :unprocessable_entity }
        format.json { render :json => @job.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.xml
  def destroy
    @job.destroy

    respond_to do |format|
      format.html { redirect_to(jobs_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :browers %><br />
    <% for browser in Useragent::BROWSER_TYPES %>
      <%= check_box_tag 'job[browsers][]', browser, @job.browsers && @job.browsers.include?(browser), :id => "job_browsers_#{browser}" %>
      <%= label_tag "job_browsers_#{browser}", browser %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :suites %><br />
    <%= f.text_area :suites, :value => @job.suites && @job.suites.map{|n, v| "#{n}: #{v}" }.join("\n") %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/_show.html.erb
<% useragents = Useragent.with_browser(job.browsers).order('id') %>
<% client_runs = ClientRun.where(:run_id => job.runs.map(&:id)).includes(:client) %>
<table>
  <tr>
    <th></th>
  <% for ua in useragents %>
    <th><%= image_tag "browsers/#{ua.engine}.sm.png", :width => 24, :height => 24, :title => ua.name %></th>
  <% end %>
  </tr>
<% for run in job.runs %>
  <tr>
    <th><%= run.name %></th>
  <%# Keep the same order as the useragents %>
  <% for uarun in run.useragent_runs.order('useragent_id') %>
    <%
      #FIXME: This is all a bit crazy
      uacrs = client_runs.select{|cr| cr.run_id == run.id && cr.client.useragent_id == uarun.useragent_id }
      uacr, total, bgcolor, color = case
        when uacrs.any?(&:failed?)
          uacr = uacrs.sort_by(&:fail).reverse.first
          [uacr, uacr.fail, 'red', 'white']
        when uacrs.any?(&:running?)
          [nil, 'R', 'yellow', 'black']
        when uacrs.first
          uacr = uacrs.sort_by(&:total).reverse.first
          [uacr, uacr.total, 'green', 'white']
        else
          [nil, '-', 'transparent', 'black']
      end
    %>
    <td style="background-color:<%= bgcolor %>; color:<%= color %>; text-align:center;"><%= link_to_if uacr.try(:results), total, uacr, :style => "color:#{color}" %></td>
  <% end %>
  </tr>
<% end %>
</table>

<%
  # TODO: Convert this to SQL
  client_runs = job.client_runs.includes(:client).select{|cr| cr.done? || cr.failed? }.group_by{|cr| cr.client.useragent_id }.values
  fails = (client_runs.flatten.sum(&:fail) / client_runs.count.to_f).round
  errors = (client_runs.flatten.sum(&:error) / client_runs.count.to_f).round
  total = (client_runs.flatten.sum(&:total) / client_runs.count.to_f).round
%>

<p>
  <b>AVERAGES:</b><br />
  <b>Fail:</b> <%= fails %><br />
  <b>Error:</b> <%= errors %><br />
  <b>Total:</b> <%= total %><br />
  <b>Pass %:</b>
  <%= (((total - fails - errors) / total.to_f) * 10000).round / 100.0 %>%
</p>

<script type="text/javascript">
  jobStatus = '<%= @job.status %>';
</script>

app/views/jobs/index.html.erb
<h1>Listing jobs</h1>

<table>
  <tr>
    <th>Date</th>
    <th>User</th>
    <th>Name</th>
    <th>Revision</th>
    <th>Status</th>
    <th>Browsers</th>
    <th>Suites</th>
    <th></th>
    <th></th>
  </tr>

<% @jobs.each do |job| %>
  <tr>
    <td><%= job.test_creation_date %></td>
    <td><%= job.user.email %></td>
    <td><%= link_to_if job.url, job.name, job.url %></td>
    <td><%= job.revision %></td>
    <td><%= job.status %></td>
    <td><%= job.browsers %></td>
    <td><%= job.suites.keys.join(', ') %></td>
    <td><%= link_to 'Show', job %></td>
    <td><%= link_to 'Destroy', job, :confirm => 'Are you sure?', :method => :delete if can? :destroy, job %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Job', new_job_path if can? :create, Job %>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/run.html.erb
<% content_for :head do %>
  <script style="text/javascript">

    var RubySwarm = {

      timeout: 20,
      timerStatusEl: null,
      runStatusEl: null,
      testEl: null,
      updateTimer: null,
      updateCountdown: null,
      currentRun: null,
      tickerTimer: null,

      testSuccess: function(msg){
        this.runStatusEl.html(msg);

        var self = this;
        setTimeout(function(){ self.startCountdown(); }, 3000);
      },

      testError: function(error){
        this.runStatusEl.html(error);

        var self = this;
        setTimeout(function(){ self.startCountdown(); }, 3000);
      },

      startCountdown: function(){
        this.updateCountdown = <%= RubySwarm::RUN_UPDATE_FREQUENCY %>;
        this.timerTick();
      },

      timerTick: function(){
        var self = this;

        if (this.tickerTimer) clearTimeout(this.tickerTimer);

        this.updateCountdown = this.updateCountdown - 1;

        if (this.updateCountdown === 0) {
          this.timerStatusEl.html('');
          this.runStatusEl.html('Finding Tests...');

          this.currentRun = new RubySwarm.Run({
            testEl: this.testEl,
            gotData: function(){ self.runStatusEl.html("Loading..."); },
            loaded: function(){ self.runStatusEl.html("Running..."); },
            success: function(msg){ self.testSuccess(msg); },
            error: function(error){ self.testError(error); }
          });
          this.currentRun.get();
        } else {
          this.timerStatusEl.html('Update in '+this.updateCountdown);
          this.tickerTimer = setTimeout(function(){ self.timerTick(); }, 1000);
        }
      },

      submitTest: function(params){
        console.log('submitTest', params);
        if (this.currentRun) {
          this.currentRun.submit(params);
        } else {
          console.error("No current test!");
        }
      },

      keepalive: function(){
        console.log('keepalive');
        if (this.currentRun) {
          this.currentRun.startTimeout();
        } else {
          console.error("No current test!");
        }
      }

    };

    RubySwarm.Run = function(attrs){
      this.testEl = attrs.testEl;
      this.gotData = attrs.gotData;
      this.loaded = attrs.loaded;
      this.success = attrs.success;
      this.error = attrs.error;
    };

    $.extend(RubySwarm.Run.prototype, {
      /**
        Get job data
      */
      get: function(){
        var self = this;
        $.ajax({
          url: '<%= get_runs_path(:format => :json) %>',
          success: function(data){ self.processData(data); },
          error: function(req, msg){ self.handleError(msg); }
        });
      },

      /**
        Process job data
      */
      processData: function(data) {
        var self = this;

        if (data.run) {
          this.gotData();

          this.id = data.run.id;
          this.testEl.attr('src', data.run.url);

          var loadFunc = function(){
            self.testEl.unbind('load', loadFunc);
            self.startTests();
          };
          this.testEl.bind('load', loadFunc);
        } else {
          this.error(data.message || "Unknown Error");
        }
      },

      /**
        Handle error
      */
      handleError: function(msg){
        this.error("Error: "+msg);
      },

      /**
        Start tests running
      */
      startTests: function(){
        var self = this, testWin;
        try {
          testWin = this.testEl[0].contentWindow;
        } catch (e){};
        if (testWin && testWin.RubySwarmRunner) {
          this.loaded();
          this.startTimeout();
        } else {
          this.error("No tests to run");
        }
      },

      startTimeout: function(){
        this.stopTimeout();

        var self = this;
        this.timeoutTimer = setTimeout(function(){ self.timedout(); }, RubySwarm.timeout * 1000);
      },

      stopTimeout: function(){
        if (this.timeoutTimer) clearTimeout(this.timeoutTimer);
      },

      timedout: function(){
        this.submit({ fail: -1, total: -1 });
      },

      /**
        Submit results
      */
      submit: function(params) {
        this.stopTimeout();

        $.ajax({
          url:  '<%= run_path('000', :format => :json) %>'.replace('000', this.id),
          type: 'POST',
          data: {
            _method: 'PUT',
            run: {
              fail: params.fail || 0,
              error: params.error || 0,
              total: params.total || 0,
              results: params.results
            }
          },
          dataType: 'json',
          success: function(){
            console.log('Success');
          },
          error: function(r, msg){
            console.log("Error: "+msg);
          }
        });
        if (params.total === -1) {
          this.error("Couldn't run tests");
        } else {
          this.success("Results -- Fail: "+params.fail+", Error: "+params.error+", Total: "+params.total);
        }
      }

    });

    $(document).ready(function(){
      RubySwarm.timerStatusEl = $('#timer_status');
      RubySwarm.runStatusEl = $('#run_status');
      RubySwarm.testEl = $('#test_runner');
      RubySwarm.startCountdown();
    });
  </script>
<% end %>

<%= @client.inspect %>

<div id="timer_status"></div>
<div id="run_status"></div>

<iframe id="test_runner" style="width: 100%; min-width: 800px; height: 600px"></iframe>

app/views/jobs/show.html.erb
<% content_for :head do %>
  <script type="text/javascript">
    $(document).ready(function(){
      console.log("ready");
      var jobStatus;
      var updateTimer = setInterval(function(){
        console.log('updateTimer');
        if (jobStatus !== '<%= Job::DONE %>') {
          $('#runs').load('<%= job_path(@job) %>');
        } else {
          clearTimer(updateTimer);
        }
      }, 30000);
    });
  </script>
<% end %>

<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @job.user_id %>
</p>

<p>
  <b>Name:</b>
  <%= @job.name.html_safe %>
</p>

<p>
  <b>Status:</b>
  <%= @job.status %>
</p>

<p>
  <b>Browsers:</b>
  <%= @job.browsers %>
</p>

<%# FIXME: This next bit is a mess %>

<b>Runs</b>

<div id="runs">
  <%= render :partial => 'show', :locals => { :job => @job } %>
</div>

<%= link_to 'Back', jobs_path %>