config/routes.rb
RubySwarm::Application.routes.draw do

  devise_for :users

  resources :useragents

  resources :jobs, :except => [:edit, :update] do
    collection do
      get 'run'
    end
  end

  resources :clients, :only => [:index, :show]

  resources :runs, :only => [:update] do
    collection do
      get 'get'
    end
  end

  resources :client_runs, :only => [:show]

  root :to => "welcome#index"

end

app/models/client.rb
class Client < ActiveRecord::Base

  TIMEOUT = 5.minutes

  belongs_to :user
  belongs_to :useragent
  has_many :client_runs, :dependent => :destroy

  attr_accessible :user_id, :useragent_id, :os, :useragentstr, :ip

  # TODO: Should we have better association validation?
  validates :user_id,      :presence => true
  validates :useragent_id, :presence => true
  validates :os,           :presence => true
  validates :useragentstr, :presence => true
  validates :ip,           :presence => true

  scope :timedout, lambda{ where("updated_at < ? AND active = ?", Time.now - TIMEOUT, true) }

  class << self

    def for_current(user, uastr, ip)
      uadata = Useragent.parse(uastr)
      useragent = Useragent.find_by_useragent(uadata)

      if useragent
        params = { :user_id => user.id, :useragent_id => useragent.id, :os => uadata[:os], :useragentstr => uastr, :ip => ip }

        # Assume expired ones have been wiped
        if existing = where(params).first
          existing.update_attribute(:active, true)
          existing
        else
          client = new(params)
          client.active = true
          client.save
          client
        end
      end
    end

    def expire
      timedout.each(&:timeout)
    end

  end

  def timeout
    update_attribute(:active, false)
    client_runs.running.destroy_all
  end

  def serializable_hash(*)
    super.except('ip')
  end

  def to_xml(options = {})
    (options[:except] ||= []) << :ip
    super
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  load_and_authorize_resource

  # GET /clients
  # GET /clients.xml
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.xml
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @client }
    end
  end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table>
  <tr>
    <th>User</th>
    <th>Useragent</th>
    <th>Os</th>
    <th>Useragent</th>
    <th>Active</th>
    <th></th>
  </tr>

<% @clients.each do |client| %>
  <tr>
    <td><%= client.user_id %></td>
    <td><%= client.useragent_id %></td>
    <td><%= client.os %></td>
    <td><%= client.useragentstr %></td>
    <td><%= client.active %></td>
    <td><%= link_to 'Show', client if can?(:read, client) %></td>
  </tr>
<% end %>
</table>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @client.user_id %>
</p>

<p>
  <b>Useragent:</b>
  <%= @client.useragent_id %>
</p>

<p>
  <b>Os:</b>
  <%= @client.os %>
</p>

<p>
  <b>Useragent:</b>
  <%= @client.useragentstr %>
</p>

<%= link_to 'Back', clients_path %>