config/routes.rb
RubySwarm::Application.routes.draw do

  devise_for :users

  resources :useragents

  resources :jobs, :except => [:edit, :update] do
    collection do
      get 'run'
    end
  end

  resources :clients, :only => [:index, :show]

  resources :runs, :only => [:update] do
    collection do
      get 'get'
    end
  end

  resources :client_runs, :only => [:show]

  root :to => "welcome#index"

end

app/models/useragent.rb
class Useragent < ActiveRecord::Base

  BROWSER_TYPES = %w(popular gbs beta mobile).freeze

  has_many :useragent_runs
  has_many :clients

  validates :name,    :presence => true, :uniqueness => true
  validates :engine,  :presence => true
  validates :version, :presence => true, :uniqueness => { :scope => :engine }

  scope :active,  where(:active => true)
  BROWSER_TYPES.each{|b| scope b, where(b => true) }
  scope :with_browser, lambda{|browserstr|
    sql = []; params = []
    BROWSER_TYPES.select{|b| (browserstr || '').include?(b) }.each{|b| sql << "#{b} = ?"; params << true }
    sql.empty? ? where("1 = 0") : where(sql.join(" OR "), *params)
  }

  class << self

    def parse(str)
      dstr = str.downcase

      version = case dstr
        when /.*(webos|fennec|series60|blackberry[0-9]*[a-z]*)[\/: ]([0-9a-z.]+)/ then $2
        when /.+(rv|applewebkit|presto|msie|konqueror)[\/: ]([0-9a-z.]+)/         then $2
        else                                                                      "unknown"
      end

      browser = case dstr
        when /msie.*windows phone/    then "winmo"
        when /msie/                   then "msie"
        when /konqueror/              then "konqueror"
        when /chrome/                 then "chrome"
        when /webos/                  then "webos"
        when /android.*mobile safari/ then "android"
        when /series60/               then "s60"
        when /blackberry/             then "blackberry"
        when /opera mobi/             then "operamobile"
        when /fennec/                 then "fennec"
        when /webkit.*mobile/         then "mobilewebkit"
        when /webkit/                 then "webkit"
        when /presto/                 then "presto"
        when /gecko/                  then "gecko"
        else                               "unknown"
      end

      os = case dstr
        when /windows nt 6\.1/ then "win7"
        when /windows nt 6\.0/ then "vista"
        when /windows nt 5\.2/ then "2003"
        when /windows nt 5\.1/ then "xp"
        when /windows nt 5\.0/ then "2000"
        when /blackberry/      then "blackberry"
        when /iphone/          then "iphone"
        when /ipod/            then "ipod"
        when /ipad/            then "ipad"
        when /symb/            then "symbian"
        when /webos/           then "webos"
        when /android/         then "android"
        when /windows phone/   then "winmo"
        when /os x 10[\._]4/   then "osx10.4"
        when /os x 10[\._]5/   then "osx10.5"
        when /os x 10[\._]6/   then "osx10.6"
        when /os x/            then "osx"
        when /linux/           then "linux"
        else                        "unknown"
      end

      { :browser => browser, :version => version, :os => os }
    end

    def find_by_useragent(str_or_hash)
      ua = str_or_hash.is_a?(Hash) ? str_or_hash : parse(str_or_hash)

      if ActiveRecord::Base.configurations[Rails.env]['adapter'] == 'mysql'
        # This assumes that the greatest alphabetical name will be the greatest version
        self.where("engine=? AND ? REGEXP version", ua[:browser], ua[:version]).order("name DESC").first
      else
        self.where(:engine => ua[:browser]).order("name DESC").detect{|u| ua[:version] =~ Regexp.new(u.version) }
      end
    end

  end

end

app/controllers/useragents_controller.rb
class UseragentsController < ApplicationController
  load_and_authorize_resource

  # GET /useragents
  # GET /useragents.xml
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @useragents }
    end
  end

  # GET /useragents/1
  # GET /useragents/1.xml
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @useragent }
    end
  end

  # GET /useragents/new
  # GET /useragents/new.xml
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @useragent }
    end
  end

  # GET /useragents/1/edit
  def edit
  end

  # POST /useragents
  # POST /useragents.xml
  def create
    respond_to do |format|
      if @useragent.save
        format.html { redirect_to(@useragent, :notice => 'Useragent was successfully created.') }
        format.xml  { render :xml => @useragent, :status => :created, :location => @useragent }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @useragent.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /useragents/1
  # PUT /useragents/1.xml
  def update
    respond_to do |format|
      if @useragent.update_attributes(params[:useragent])
        format.html { redirect_to(@useragent, :notice => 'Useragent was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @useragent.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /useragents/1
  # DELETE /useragents/1.xml
  def destroy
    @useragent.destroy

    respond_to do |format|
      format.html { redirect_to(useragents_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/useragents_helper.rb
module UseragentsHelper
end

app/views/useragents/_form.html.erb
<%= form_for(@useragent) do |f| %>
  <% if @useragent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@useragent.errors.count, "error") %> prohibited this useragent from being saved:</h2>

      <ul>
      <% @useragent.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :engine %><br />
    <%= f.text_field :engine %>
  </div>
  <div class="field">
    <%= f.label :version %><br />
    <%= f.text_field :version %>
  </div>
  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :current %>
    <%= f.check_box :current %>
  </div>
  <div class="field">
    <%= f.label :popular %>
    <%= f.check_box :popular %>
  </div>
  <div class="field">
    <%= f.label :gbs %>
    <%= f.check_box :gbs %>
  </div>
  <div class="field">
    <%= f.label :beta %>
    <%= f.check_box :beta %>
  </div>
  <div class="field">
    <%= f.label :mobile %>
    <%= f.check_box :mobile %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/useragents/edit.html.erb
<h1>Editing useragent</h1>

<%= render 'form' %>

<%= link_to 'Show', @useragent %> |
<%= link_to 'Back', useragents_path %>

app/views/useragents/index.html.erb
<h1>Listing useragents</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Engine</th>
    <th>Version</th>
    <th>Active</th>
    <th>Current</th>
    <th>Popular</th>
    <th>Gbs</th>
    <th>Beta</th>
    <th>Mobile</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @useragents.each do |useragent| %>
  <tr>
    <td><%= useragent.name %></td>
    <td><%= useragent.engine %></td>
    <td><%= useragent.version %></td>
    <td><%= useragent.active %></td>
    <td><%= useragent.current %></td>
    <td><%= useragent.popular %></td>
    <td><%= useragent.gbs %></td>
    <td><%= useragent.beta %></td>
    <td><%= useragent.mobile %></td>
    <td><%= link_to 'Show', useragent %></td>
    <td><%= link_to 'Edit', edit_useragent_path(useragent) if can? :edit, useragent %></td>
    <td><%= link_to 'Destroy', useragent, :confirm => 'Are you sure?', :method => :delete if can? :destroy, useragent %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Useragent', new_useragent_path if can? :create, Useragent %>

app/views/useragents/new.html.erb
<h1>New useragent</h1>

<%= render 'form' %>

<%= link_to 'Back', useragents_path %>

app/views/useragents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @useragent.name %>
</p>

<p>
  <b>Engine:</b>
  <%= @useragent.engine %>
</p>

<p>
  <b>Version:</b>
  <%= @useragent.version %>
</p>

<p>
  <b>Active:</b>
  <%= @useragent.active %>
</p>

<p>
  <b>Current:</b>
  <%= @useragent.current %>
</p>

<p>
  <b>Popular:</b>
  <%= @useragent.popular %>
</p>

<p>
  <b>Gbs:</b>
  <%= @useragent.gbs %>
</p>

<p>
  <b>Beta:</b>
  <%= @useragent.beta %>
</p>

<p>
  <b>Mobile:</b>
  <%= @useragent.mobile %>
</p>


<%= link_to 'Edit', edit_useragent_path(@useragent) %> |
<%= link_to 'Back', useragents_path %>